name: Daily Upload Tracker

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at midnight every day
  workflow_dispatch: 

jobs:
  update-streak:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Get Current Date
      run: |
        echo "Current Date: $(date)"
        echo "Streak updated on $(date)" >> streak.txt

    - name: Commit Streak Update
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add streak.txt
        git commit -m "Update streak count"
        git push
